#append(), insert(), remove(), pop(), clear(), sort(), reverse()
L5=[5,1,23,6,0,66,25]
print("Append an element 500 to List L5:")
L5.append(500)
print("L5 after appending element 500:",L5)
print("Insert 999 at the index 5 L5:")
L5.insert(5,999)
print("L5 after inserting 999 at index 5:",L5)
print("Remove 25 from List L5:")
L5.remove(25)
print("L5 after removing 25:",L5)
print("Pop an element with index 2 from List L5:",L5.pop(2))
print("L5 after popping an element at index 2:",L5)
print("Index of specified element 6:",L5.index(6))
print("Get the count of element 6 that appears in L5:",L5.count(6))
print("Elements after sorting in L5:")
print(L5.sort())
print("Elements after reversing the elements in L5:")
print(L5.reverse())
