T4=(5,1,23,6,1,66,25)
#len(), max(), min()
print("Length of a given Tuple T4 is:",len(T4))
print("Max element in a given Tuple T4 is:",max(T4))
print("Min element in a given Tuple T4 is",min(T4))
print("Sum of all elements in a given Tuple T4 is",sum(T4))
print("any=",any(T4))
print("All=",all(T4))
print("Elements of T4 after sorting are:",sorted(T4))
